//
//  Terms of Use.swift
//  Gym-app-ioss
//
//  Created by Daniel Pinilla on 6/18/25.
//

import SwiftUI

struct Terms_of_Use: View {
    var body: some View {
        ZStack{
            LinearGradient(colors: [Color.blue.opacity(0.7),Color.purple.opacity(0.7)],startPoint: .topLeading,endPoint: .bottomTrailing).ignoresSafeArea()
            Circle().frame(width: 300).foregroundStyle(Color.blue.opacity(0.3)).blur(radius: 10).offset(x: -10, y: -150)
            Circle().frame(width: 300).foregroundStyle(Color.white.opacity(0.3)).blur(radius: 10).offset(x: 10, y: 250)
            VStack{
                Text("Terms of Use").font(.title).fontDesign(.rounded).bold().foregroundStyle(Color.white)
             Spacer()
                Text("By proceeding, you acknowledge that PowAI collects and stores your account data solely to provide app features like AI‑generated workouts, live activity tracking, and nutrition logs as described in the README. Workout and nutrition plans are generated by an AI model and are not licensed professional advice, we remind users that such plans are \(Text("a general guideline").foregroundStyle(Color.red).bold()) and it is not a substitute for professional medical advice, diagnosis, or treatment. \(Text("It is essential to consult with a qualified healthcare professional before making significant changes to your diet or exercise routine").foregroundStyle(Color.red)). You agree that PowAI does not endorse any specific diet or exercise program. You agree not to hold PowAI responsible for any health outcomes and understand that your data will not be repurposed for other services.").multilineTextAlignment(.center).frame(width: 340.0).fontDesign(.rounded).foregroundStyle(Color.white).background(RoundedRectangle(cornerRadius: 20).fill(.ultraThinMaterial).frame(width: 370, height: 470))
                Spacer()
            }
        }
    }
}

#Preview {
    Terms_of_Use()
}
